### ISSUE TITLE
NoneType error at /matches/

### ISSUE THREAD

**Issue by Kapn** [grepthink/grepthink#112]
Internal Server Error: /matches/

AttributeError at /matches/ ‘NoneType’ object has no attribute ‘limit_weights’

Request Method: GET Request URL: https://www.grepthink.com/matches/ Django Version: 1.10.5 Python Executable: /app/.heroku/python/bin/python Python Version: 3.6.0 Python Path: ['/app', ‘/app/.heroku/python/bin’, ‘/app’, ‘/app/.heroku/python/lib/python36.zip’, ‘/app/.heroku/python/lib/python3.6’, ‘/app/.heroku/python/lib/python3.6/lib-dynload’, ‘/app/.heroku/python/lib/python3.6/site-packages’] Server time: Sat, 12 May 2018 01:23:03 +0000 Installed Applications: ['django.contrib.auth',

'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.messages',
'whitenoise.runserver_nostatic',
'django.contrib.staticfiles',
'teamwork.apps.core',
'teamwork.apps.profiles',
'teamwork.apps.projects',
'teamwork.apps.courses',
'django_adminlte',
'django_adminlte_theme',
'django.contrib.admin',
'django_gravatar',
'chartjs']
Installed Middleware: ['django.middleware.security.SecurityMiddleware',

'whitenoise.middleware.WhiteNoiseMiddleware',
'django.contrib.sessions.middleware.SessionMiddleware',
'django.middleware.common.CommonMiddleware',
'django.middleware.csrf.CsrfViewMiddleware',
'django.contrib.auth.middleware.AuthenticationMiddleware',
'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
'django.contrib.messages.middleware.MessageMiddleware',
'django.middleware.clickjacking.XFrameOptionsMiddleware']
Traceback:

File “/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/exception.py” in inner

39.             response = get_response(request)
File “/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py” in _legacy_get_response

249.             response = self._get_response(request)
File “/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py” in _get_response

187.                 response = self.process_exception_by_middleware(e, request)
File “/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py” in _get_response

185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)
File “/app/.heroku/python/lib/python3.6/site-packages/django/contrib/auth/decorators.py” in _wrapped_view

23.                 return view_func(request, *args, **kwargs)
File “/app/teamwork/apps/core/views.py” in view_matches

154.             p_match = po_match(project)
File “/app/teamwork/apps/core/models.py” in po_match

51.     if course.limit_weights:
Exception Type: AttributeError at /matches/ Exception Value: ‘NoneType’ object has no attribute ‘limit_weights’ Request information: USER: mgates

GET: No GET data

POST: No POST data

FILES: No FILES data

**Comment by rmonroe** [comment]
Believe this was addressed in previous match overhaul
