### ISSUE TITLE
Project divs are all different sizes based on amount of text in title

### ISSUE THREAD

**Issue by Kapn** [grepthink/grepthink#119]
![image](https://user-images.githubusercontent.com/6921374/40866649-af7861be-65b3-11e8-9658-e25a670cb9b1.png)

![image](https://user-images.githubusercontent.com/6921374/40866653-b9611f68-65b3-11e8-9439-4eeadbd24388.png)

Changes based on screen width, need to make sure all divs are the same height.

**Comment by rmonroe** [comment]
Partial Fix complete. If the text will overflow over 1 line the end is trimmed and an ellipsis is added to the end. I tried for days to get the css to work for it to scroll the rest on hover, but something in the framework overwrites this. So for now we just have the ellipsis and all the cards are the same
