### ISSUE TITLE
view_one_course is throwing the 'NoneType' object has no attribute 'role' usual error.

### ISSUE THREAD

**Issue by Kapn** [grepthink/grepthink#81]
* Needs small adjustment. Line 182

**Comment by Kapn** [comment]
Check Internal Server Error logs.

**Comment by andgates** [comment]
@Kapn I couldn't reproduce this on the live site

**Comment by Kapn** [comment]
me neither. But students are getting the error. Just got another email yesterday. @andgates

**Comment by Kapn** [comment]
haven't gotten an email in a while and a similar task is Done in 'Bugs'. Closing this
