### ISSUE TITLE
Container background

### ISSUE THREAD

**Issue by Kapn** [grepthink/grepthink#98]
White background of container is lost. Intentional?
Project View:
![image](https://user-images.githubusercontent.com/6921374/38438695-16bab9da-3990-11e8-94d6-990a865229fb.png)

Versus the Course View:
![image](https://user-images.githubusercontent.com/6921374/38438721-2a7f68d0-3990-11e8-88ef-abb6b9acc8e3.png)

**Comment by rmonroe** [comment]
I would say this is intentional, given the tabs for a course are not in a white container either. I did, however, put the description in a container similar to the other tabs leaving the updates out of it since this should grow
